r'''
    TEXTBLOCK

    Your task is create a class TextBlock that represents a rectangular block 
    of text. The class should contain the following four methods: 
    __init__, __add__, __or__, and __str__. 

      TextBlock(text) 

        Should create a new TextBlock object with the given text. The text 
        should be able to be one or more lines of text separated by '\n'.
        Each line must be non-empty and have the same length. 
        E.g., TextBlock('ABC\nDEF') should create a TextBlock object with two
        lines of text, each containing three characters.
    
      x + y

        Given two TextBlock objects x and y, x + y should return a new TextBlock,
        containing the lines of text from x followed by the lines of text from y.
        E.g., TextBlock('A\nB') + TextBlock('C\nD') should return 
        TextBlock('A\nB\nC\nD').

      x | y
    
        Given two TextBlock objects x and y, x | y should return a new TextBlock,
        where each line of text in the new TextBlock is the concatenation of the
        corresponding lines of text in x and y. E.g., 
        TextBlock('A\nB') | TextBlock('C\nD') should return TextBlock('AC\nBD').

      str(x)
        
        Given a TextBlock object x, str(x) should return the text of the 
        TextBlock, where lines are separated by '\n'.

    If the text input to the TextBlock constructor is not a valid block of text,
    the constructor should raise a ValueError.  Similarly, if the texts to 
    + and | do not have the same width or height, respectively, a ValueError
    should be raised.

    Input:  Multiple lines of Python code using the class TextBlock.
            The last line starts with '#eof' (indicating end of file).

    Output: The output generated by executing the input code.

    Example:

      Input:  x = TextBlock('A')  # x = 'A'
              y = TextBlock('B')  # y = 'B'
              z = x | y | y | x   # z = 'ABBA' 
              w = z + z + z       # w = 'ABBA\nABBA\nABBA'
              print(w)
              #eof

      Output: ABBA
              ABBA
              ABBA

    Note: The below code already handles reading and executing the input.             
'''


class TextBlock:
    # insert code
    pass


import sys
code = ''
for line in sys.stdin:
    code += line
    if line.startswith('#eof'):
        break
exec(code)
