r'''
    SAME TREE

    We say that two binary trees are the same if they are equal up to
    swapping left and right children of some nodes. For example, the trees
    tree1 and tree2 are the same, whereas tree3 is not the same as any
    of the two other trees.
    
    	        tree1                   tree2                   tree3

    	         /\                      /\                      /\           
    	        /  \                    /  \                    /  \      
    	       /    \                  /    \                  /    \     
    	      /      \                /      \                /      \    
    	     /        \              /        \              /        \   
    	    / \      / \            / \      / \            / \      / \  
    	  'A' 'B'  'C' 'D'        'C' 'D'  'B' 'A'        'A' 'D'  'C' 'B'

    	(('A','B'),('C','D'))   (('C','D'),('B','A'))   (('A','D'),('C','B'))

    Your task is to write a function same(tree1, tree2) that returns True
    if the two trees are the same, otherwise False. The trees are assumed
    to be binary trees where each leaf has a unique label.
          
    Input:  Multiple lines of Python code using the function same.
            The last line should start with '#eof' (indicating end of file).
            Each tree is guaranteed to have at most 100 leaves.

    Output: The output generated by executing the input code.
    
    Example:

      Input:  tree1 = (('A', 'B'), ('C', 'D'))
              tree2 = (('C', 'D'), ('B', 'A'))
              tree3 = (('A', 'D'), ('C', 'B'))
              print(same(tree1, tree2))
              print(same(tree1, tree3))
              print(same(tree2, tree3))
              #eof

      Output: True
              False
              False

    Note: The below code already handles reading and executing the input.                 
'''


def same(tree1, tree2):
    # insert code
    pass


import sys
code = ''
for line in sys.stdin:
    code += line
    if line.startswith('#eof'):
        break
exec(code)
